// Wizard configuration constants
// Source of truth for wizard-related constants

import { ENV } from "../env";
import { SHARED_DEFAULTS } from "@blueprint/shared";

/**
 * Wizard step configuration
 * Defines the ordered steps in the project setup wizard
 */
export const WIZARD_STEPS = [
  { key: "info", label: "Project Info", icon: "📝", shortcut: "1" },
  { key: "stack", label: "Tech Stack", icon: "⚙️", shortcut: "2" },
  { key: "features", label: "Features", icon: "✨", shortcut: "3" },
  { key: "review", label: "Review", icon: "👀", shortcut: "4" },
  { key: "generating", label: "Generate", icon: "🚀", shortcut: "5" },
] as const;

/**
 * Tech stack category icons
 * Maps category keys to their emoji representations
 */
export const CATEGORY_ICONS: Record<string, string> = {
  frontend: "🎨",
  backend: "⚙️",
  database: "🗄️",
  hosting: "☁️",
  styling: "🖌️",
  ai: "🤖",
  testing: "🧪",
  other: "📦",
} as const;

/**
 * UI emoji constants - centralized for consistency
 * Used across components for consistent emoji rendering
 */
export const UI_EMOJIS = {
  /** Document/editing icon */
  DOCUMENT: "📝",
  /** Blank document icon */
  DOCUMENT_BLANK: "📄",
  /** Settings/gear icon */
  SETTINGS: "⚙️",
} as const;

/**
 * Minimum requirements for wizard validation
 * Defines the minimum counts/values for a valid project configuration
 */
export const MIN_REQUIREMENTS = {
  TECH_STACK: 1,
  PROJECT_NAME: 1,
  DESCRIPTION: 10,
} as const;

/**
 * Export configuration
 * Settings for ZIP compression, file naming, and export behavior
 */
export const EXPORT_CONFIG = {
  ZIP_COMPRESSION_LEVEL: 6,
  COPY_TEXTAREA_OFFSET: -9999,
  README_FILENAME: "README.md",
  METADATA_FILENAME: "metadata.json",
  BLUEPRINT_FILENAME: "blueprint.md",
  TASK_FILENAME: "task.md",
  METADATA_VERSION: SHARED_DEFAULTS.API_VERSION,
  DOCS_FOLDER: ".docs",
  ZIP_FILENAME_SUFFIX: ".zip",
  DATE_FORMAT_SEPARATOR: "T",
} as const;

/**
 * Suggested features for quick add
 * Pre-defined feature suggestions displayed in the features step
 */
export const SUGGESTED_FEATURES = [
  "User authentication",
  "Database integration",
  "API endpoints",
  "Real-time updates",
  "File uploads",
  "Search functionality",
  "Email notifications",
  "Admin dashboard",
  "Payment processing",
  "Analytics tracking",
] as const;

/**
 * Editor tab constants
 * Identifiers for the split-pane editor tabs
 */
export const EDITOR_TABS = {
  BLUEPRINT: "blueprint",
  TASKS: "tasks",
} as const;

/**
 * Generates a README template for project documentation
 * @param projectName - The name of the project
 * @returns Formatted README markdown string
 */
export const README_TEMPLATE = (projectName: string): string => {
  const homepageUrl = ENV.PROJECT_HOMEPAGE_URL;
  return `# ${projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [${ENV.APP_NAME}](${homepageUrl})
Generated at: ${new Date().toISOString()}
`;
};

/** Default project name fallback */
export const DEFAULT_PROJECT_NAME = ENV.DEFAULT_PROJECT_NAME;

/**
 * Tech stack project type detection rules
 * Maps technology names to project type identifiers for export scaffolding
 * Flexy says: No hardcoded tech names - everything in config!
 */
export const TECH_STACK_DETECTION = {
  /** Technologies that indicate a React/Next.js project */
  REACT_INDICATORS: ["react", "next.js"] as const,
  /** Technologies that indicate a Node.js/Express project */
  NODE_INDICATORS: ["node.js", "express", "hono"] as const,
  /** Technologies that indicate a Python/Django project */
  PYTHON_INDICATORS: ["python", "django", "flask"] as const,
} as const;
