/**
 * Frontend configuration constants
 * Centralized location for all hardcoded values
 */

// Form validation limits
export const FORM_LIMITS = {
  PROJECT_NAME: {
    MIN: 1,
    MAX: 100,
    WARNING_THRESHOLD: 90,
  },
  DESCRIPTION: {
    MIN: 10,
    MAX: 2000,
  },
  TARGET_AUDIENCE: {
    MAX: 200,
  },
  CONSTRAINTS: {
    MAX: 1000,
  },
  FEATURE: {
    MAX: 100,
    MAX_COUNT: 20,
  },
} as const;

// Animation durations (in seconds)
export const ANIMATION = {
  FAST: 0.2,
  NORMAL: 0.3,
  SLOW: 0.5,
  STAGGER: 0.1,
  SPINNER_ROTATION: 1,
} as const;

// Timeouts (in milliseconds)
export const TIMEOUTS = {
  COPY_FEEDBACK: 2000,
  DEBOUNCE: 300,
  GENERATION_CHECK: 100,
  TOAST_NOTIFICATION: 1500,
} as const;

// UI Configuration
export const UI = {
  MAX_TECH_STACK_SELECTION: 10,
  TOOLTIP_DELAY: 500,
  SCROLL_OFFSET: 100,
} as const;

// Step configuration
export const WIZARD_STEPS = [
  { key: "info", label: "Project Info", icon: "📝", shortcut: "1" },
  { key: "stack", label: "Tech Stack", icon: "⚙️", shortcut: "2" },
  { key: "features", label: "Features", icon: "✨", shortcut: "3" },
  { key: "review", label: "Review", icon: "👀", shortcut: "4" },
  { key: "generating", label: "Generate", icon: "🚀", shortcut: "5" },
] as const;

// Tech stack category icons
export const CATEGORY_ICONS: Record<string, string> = {
  frontend: "🎨",
  backend: "⚙️",
  database: "🗄️",
  hosting: "☁️",
  styling: "🖌️",
  ai: "🤖",
  testing: "🧪",
  other: "📦",
} as const;

// Minimum requirements
export const MIN_REQUIREMENTS = {
  TECH_STACK: 1,
  PROJECT_NAME: 1,
  DESCRIPTION: 10,
} as const;

// HTTP Status codes for retry logic
export const RETRYABLE_STATUS_CODES = [408, 429, 500, 502, 503, 504] as const;

// Export configuration
export const EXPORT_CONFIG = {
  ZIP_COMPRESSION_LEVEL: 6,
  COPY_TEXTAREA_OFFSET: -9999,
} as const;

// Suggested features for quick add
export const SUGGESTED_FEATURES = [
  "User authentication",
  "Database integration",
  "API endpoints",
  "Real-time updates",
  "File uploads",
  "Search functionality",
  "Email notifications",
  "Admin dashboard",
  "Payment processing",
  "Analytics tracking",
] as const;

// Generation timing estimates
export const GENERATION_ESTIMATES = {
  TYPICAL_DURATION_SECONDS: "30-60",
  SHORT: "15-30",
  LONG: "60-90",
} as const;

// API Error messages
export const API_ERROR_MESSAGES = {
  GENERATION_FAILED: "Generation failed",
  TASK_GENERATION_FAILED: "Task generation failed",
  REFINEMENT_FAILED: "Refinement failed",
  NO_RESPONSE_BODY: "No response body",
  STREAM_ERROR: "Stream error",
} as const;

// SSE Stream configuration
export const SSE_CONFIG = {
  DATA_PREFIX: "data: ",
  EVENT_SEPARATOR: "\n\n",
  EVENT_TYPES: {
    CONTENT: "content",
    ERROR: "error",
    DONE: "done",
  },
} as const;

// Export README template
export const README_TEMPLATE = (
  projectName: string,
): string => `# ${projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`;

// Default project name fallback
export const DEFAULT_PROJECT_NAME = "my-project";

// API endpoints
export const API_ENDPOINTS = {
  GENERATE: "/generate",
  TASKS: "/tasks",
  REFINE: "/refine",
  HEALTH: "/",
} as const;
