/**
 * Frontend configuration constants
 * Centralized location for all hardcoded values
 */

// Form validation limits
export const FORM_LIMITS = {
  PROJECT_NAME: {
    MIN: 1,
    MAX: 100,
    WARNING_THRESHOLD: 90,
  },
  DESCRIPTION: {
    MIN: 10,
    MAX: 2000,
  },
  TARGET_AUDIENCE: {
    MAX: 200,
  },
  CONSTRAINTS: {
    MAX: 1000,
  },
  FEATURE: {
    MAX: 100,
    MAX_COUNT: 20,
  },
} as const;

// Animation durations (in seconds)
export const ANIMATION = {
  FAST: 0.15,
  NORMAL: 0.2,
  MEDIUM: 0.3,
  SLOW: 0.5,
  STAGGER: 0.1,
  SPINNER_ROTATION: 1,
  TYPING_INDICATOR_DELAY_S: 0.6,
} as const;

// Animation durations (in milliseconds)
export const ANIMATION_MS = {
  TYPING_INDICATOR_DELAY: 600,
  TYPING_INDICATOR_TIMEOUT: 800,
  CHIP_SELECT_FEEDBACK: 600,
} as const;

// Spring configurations for animations
export const SPRING_CONFIG = {
  DEFAULT: { stiffness: 400, damping: 25, mass: 0.8 },
  BOUNCY: { stiffness: 500, damping: 10, mass: 0.8 },
  SMOOTH: { stiffness: 500, damping: 25, mass: 0.8 },
  REDUCED_MOTION: { stiffness: 1000, damping: 100, mass: 0.1 },
} as const;

// Timeouts (in milliseconds)
export const TIMEOUTS = {
  COPY_FEEDBACK: 2000,
  DEBOUNCE: 300,
  GENERATION_CHECK: 100,
  TOAST_NOTIFICATION: 1500,
  SHAKE_ANIMATION: 400,
  FOCUS_DELAY: 100,
  LIVE_REGION_CLEAR: 1000,
  API_HEALTH_CHECK: 5000,
  API_CONNECTION: 30000,
  RIPPLE_EFFECT: 600,
  COPY_BUTTON_RESET: 700,
  RANDOM_DURATION_BASE: 400,
  RANDOM_DURATION_VARIANCE: 200,
} as const;

// UI Configuration
export const UI = {
  MAX_TECH_STACK_SELECTION: 10,
  TOOLTIP_DELAY: 500,
  TOOLTIP_DELAY_SHORT: 300,
  TOOLTIP_DELAY_LONG: 400,
  SMART_TOOLTIP_DELAY: 400,
  SCROLL_OFFSET: 100,
  SCROLL_SHOW_AFTER: 400,
  SCROLL_SHOW_AFTER_LONG: 600,
  EDITOR_SHOW_AFTER: 600,
} as const;

// Step configuration
export const WIZARD_STEPS = [
  { key: "info", label: "Project Info", icon: "📝", shortcut: "1" },
  { key: "stack", label: "Tech Stack", icon: "⚙️", shortcut: "2" },
  { key: "features", label: "Features", icon: "✨", shortcut: "3" },
  { key: "review", label: "Review", icon: "👀", shortcut: "4" },
  { key: "generating", label: "Generate", icon: "🚀", shortcut: "5" },
] as const;

// Tech stack category icons
export const CATEGORY_ICONS: Record<string, string> = {
  frontend: "🎨",
  backend: "⚙️",
  database: "🗄️",
  hosting: "☁️",
  styling: "🖌️",
  ai: "🤖",
  testing: "🧪",
  other: "📦",
} as const;

// Minimum requirements
export const MIN_REQUIREMENTS = {
  TECH_STACK: 1,
  PROJECT_NAME: 1,
  DESCRIPTION: 10,
} as const;

// HTTP Status codes for retry logic
export const RETRYABLE_STATUS_CODES = [408, 429, 500, 502, 503, 504] as const;

// Export configuration
export const EXPORT_CONFIG = {
  ZIP_COMPRESSION_LEVEL: 6,
  COPY_TEXTAREA_OFFSET: -9999,
} as const;

// Suggested features for quick add
export const SUGGESTED_FEATURES = [
  "User authentication",
  "Database integration",
  "API endpoints",
  "Real-time updates",
  "File uploads",
  "Search functionality",
  "Email notifications",
  "Admin dashboard",
  "Payment processing",
  "Analytics tracking",
] as const;

// Generation timing estimates
export const GENERATION_ESTIMATES = {
  TYPICAL_DURATION_SECONDS: "30-60",
  SHORT: "15-30",
  LONG: "60-90",
} as const;

// API Error messages
export const API_ERROR_MESSAGES = {
  GENERATION_FAILED: "Generation failed",
  TASK_GENERATION_FAILED: "Task generation failed",
  REFINEMENT_FAILED: "Refinement failed",
  NO_RESPONSE_BODY: "No response body",
  STREAM_ERROR: "Stream error",
} as const;

// SSE Stream configuration
export const SSE_CONFIG = {
  DATA_PREFIX: "data: ",
  EVENT_SEPARATOR: "\n\n",
  EVENT_TYPES: {
    CONTENT: "content",
    ERROR: "error",
    DONE: "done",
  },
} as const;

// Export README template
export const README_TEMPLATE = (
  projectName: string,
): string => `# ${projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`;

// Default project name fallback
export const DEFAULT_PROJECT_NAME = "my-project";

// API endpoints
export const API_ENDPOINTS = {
  GENERATE: "/generate",
  TASKS: "/tasks",
  REFINE: "/refine",
  HEALTH: "/",
} as const;

// Toast configuration
export const TOAST_CONFIG = {
  DEFAULT_DURATION: 3000,
  SUCCESS_DURATION: 2000,
  AUTO_SAVE_DURATION: 2000,
  ICONS: {
    SUCCESS: "✓",
    ERROR: "✕",
    WARNING: "⚠",
    INFO: "ℹ",
  } as const,
  STYLES: {
    SUCCESS:
      "bg-accent-emerald/10 border-accent-emerald/30 text-accent-emerald",
    ERROR: "bg-accent-pink/10 border-accent-pink/30 text-accent-pink",
    WARNING: "bg-yellow-500/10 border-yellow-500/30 text-yellow-400",
    INFO: "bg-primary-500/10 border-primary-500/30 text-primary-300",
  } as const,
} as const;

// Auto-save configuration
export const AUTO_SAVE_CONFIG = {
  DEFAULT_MESSAGE: "Changes saved",
  DEFAULT_DELAY: 1000,
} as const;

// Document title configuration
export const DOCUMENT_TITLE_CONFIG = {
  APP_NAME: "Blueprintify",
  SEPARATOR: " | ",
  DEFAULT_TITLE: "Blueprintify",
} as const;

// LocalStorage keys
export const STORAGE_KEYS = {
  WIZARD: "blueprint-wizard",
  EDITOR: "blueprint-editor",
} as const;

// Generation messages
export const GENERATION_MESSAGES = {
  CANCELLED: "Generation cancelled",
  BLUEPRINT_START: "Generating blueprint...",
  BLUEPRINT_COMPLETE: "Blueprint complete. Generating tasks...",
  COMPLETE: "Complete!",
  RETRY: (attempt: number, maxRetries: number) =>
    `Connection issue, retrying (${attempt}/${maxRetries})...`,
  ERROR: (error: string) => `Error: ${error}`,
  ERROR_TASKS: (error: string) => `Error generating tasks: ${error}`,
} as const;

// UI Content - Text content for the application
export const UI_CONTENT = {
  APP: {
    NAME: "Blueprint Generator",
    TAGLINE: "AI-Powered Project Architecture",
  },
  HERO: {
    TITLE_1: "From ",
    TITLE_HIGHLIGHT_1: "Idea",
    TITLE_2: " to ",
    TITLE_HIGHLIGHT_2: "Blueprint",
    TITLE_3: " in Seconds",
    SUBTITLE:
      "Generate production-ready architectural documentation for your projects. Powered by AI, designed for autonomous development.",
  },
  EDITOR: {
    EMPTY_STATE: {
      ICON: "📝",
      TITLE: "Your generated content will appear here",
      SUBTITLE: "Complete the wizard to get started",
    },
    LOADING: "Loading Editor...",
    SHOW_EDITOR_BUTTON: "Show Editor",
  },
  FOOTER: {
    BUILT_WITH: "Built with ⚡ Cloudflare Workers + React",
    COPYRIGHT: "© 2024 Blueprint Generator",
  },
  BUTTONS: {
    GITHUB: "GitHub",
    HIDE_EDITOR: "Hide editor",
    COPY: "Copy",
    EXPORT: "Export",
    NEW_PROJECT: "New Project",
    BACK: "Back",
    NEXT: "Next",
    CLEAR_ALL: "Clear all",
  },
  TEMPLATES_DIVIDER: "— or start from scratch —",
  WIZARD: {
    STEP_INFO: {
      TITLE: "Tell us about your project",
      SUBTITLE:
        "We'll use this information to generate a tailored architecture blueprint.",
      PROJECT_NAME_LABEL: "Project Name",
      PROJECT_NAME_PLACEHOLDER: "my-awesome-project",
      DESCRIPTION_LABEL: "Project Description",
      DESCRIPTION_PLACEHOLDER:
        "Describe what your project does, its main purpose, and key functionality...",
      TARGET_AUDIENCE_LABEL: "Target Audience",
      TARGET_AUDIENCE_PLACEHOLDER:
        "e.g., Developers, Small businesses, Enterprise teams",
      CONSTRAINTS_LABEL: "Constraints or Requirements",
      CONSTRAINTS_PLACEHOLDER:
        "e.g., Must be serverless, needs to support 10k concurrent users, budget limitations...",
      NEXT_BUTTON: "Next: Choose Tech Stack",
    },
    STEP_STACK: {
      TITLE: "Choose your tech stack",
      SUBTITLE:
        "Select at least 1 technology to proceed. This helps generate accurate architecture.",
      SEARCH_PLACEHOLDER: "Search technologies...",
      SELECTED_COUNT: (count: number) => `${count} selected`,
      SELECTED_LABEL: (count: number) => `Selected (${count}):`,
      NEXT_BUTTON: "Next: Add Features",
    },
    STEP_FEATURES: {
      TITLE: "Add key features",
      SUBTITLE:
        "List the main features your project should have. This helps prioritize tasks.",
      ADD_FEATURE_LABEL: "Add a feature",
      ADD_FEATURE_PLACEHOLDER: "e.g., Real-time notifications",
      FEATURES_COUNT: (count: number) => `${count} features`,
      YOUR_FEATURES_LABEL: "Your features",
      QUICK_ADD_LABEL: "Quick add suggestions",
      ADDED_MESSAGE: (feature: string) => `Added "${feature}"`,
      NEXT_BUTTON: "Next: Review",
      CLEAR_ALL_FEATURES: "Clear all features",
    },
    STEP_REVIEW: {
      TITLE: "Review your configuration",
      SUBTITLE: "Double-check everything before generating your blueprint.",
      GENERATE_BUTTON: "Generate Blueprint",
    },
  },
} as const;

// Validation messages
export const VALIDATION_MESSAGES = {
  DESCRIPTION_MIN_LENGTH: (min: number) =>
    `Description must be at least ${min} characters`,
  APPROACHING_CHARACTER_LIMIT: "Approaching character limit",
  CHARACTERS_NEEDED: (count: number) => `${count} more characters needed`,
} as const;

// Keyboard shortcuts
export const KEYBOARD_SHORTCUTS = {
  TOGGLE_EDITOR: {
    KEY: "e",
    MODIFIER: "ctrl/cmd",
    DESCRIPTION: "Toggle editor visibility",
  },
  CANCEL_GENERATION: {
    KEY: "Escape",
    DESCRIPTION: "Cancel generation",
  },
} as const;

// Animation delays for staggered effects (in seconds)
export const ANIMATION_DELAYS = {
  STAGGER_FAST: 0.1,
  STAGGER_DEFAULT: 0.2,
  STAGGER_SLOW: 0.4,
  STAGGER_SLOWER: 0.6,
  STAGGER_SLOWEST: 0.8,
} as const;

// Animation durations for specific effects (in seconds)
export const ANIMATION_DURATIONS = {
  FLOATING_ANIMATION: 3,
  PROGRESS_BAR: 2,
  CELEBRATION_DURATION: 2.5,
  DOCUMENT_FLOAT: 2.2,
  DOCUMENT_FLOAT_2: 1.8,
  PULSE_ANIMATION: 1,
  PULSE_ANIMATION_SLOW: 1.5,
  TOOLBAR_INDICATOR: 0.3,
  TOOLBAR_INDICATOR_DELAY: 0.1,
  TOOLBAR_FADE: 0.2,
  TOOLBAR_EXPAND: 0.5,
  TOOLBAR_SLIDE: 0.4,
  STEP_FADE: 0.15,
} as const;

// CSS Class combinations for common patterns
export const CSS_CLASSES = {
  GLASS_CARD: "glass-card",
  BTN_PRIMARY: "btn-primary",
  BTN_GHOST: "btn-ghost",
  TEXT_GRADIENT: "text-gradient",
  ANIMATED_SPINNER:
    "animate-spin rounded-full h-8 w-8 border-b-2 border-primary-500",
} as const;

// Focusable element selectors for accessibility
export const FOCUSABLE_SELECTORS = [
  'button:not([disabled]):not([aria-hidden="true"])',
  'a[href]:not([aria-hidden="true"])',
  'input:not([disabled]):not([type="hidden"]):not([aria-hidden="true"])',
  'select:not([disabled]):not([aria-hidden="true"])',
  'textarea:not([disabled]):not([aria-hidden="true"])',
  '[tabindex]:not([tabindex="-1"]):not([disabled]):not([aria-hidden="true"])',
  '[contenteditable]:not([aria-hidden="true"])',
] as const;

export const FOCUSABLE_SELECTOR_STRING = FOCUSABLE_SELECTORS.join(", ");

// Celebration colors for particle animations
export const CELEBRATION_COLORS = [
  "#10b981", // emerald-500
  "#34d399", // emerald-400
  "#6ee7b7", // emerald-300
  "#6366f1", // indigo-500
  "#818cf8", // indigo-400
  "#a78bfa", // violet-400
  "#f472b6", // pink-400
  "#fbbf24", // amber-400
] as const;

// Animation colors for value change indicators
export const ANIMATION_COLORS = {
  POSITIVE: "#10b981",
  NEGATIVE: "#f43f5e",
} as const;

// External URLs used throughout the application
export const EXTERNAL_URLS = {
  GITHUB: "https://github.com",
  PROJECT_HOMEPAGE: "https://blueprint-generator.pages.dev",
} as const;

// UI Fallback values for environment-dependent configs
export const UI_FALLBACKS = {
  API_BASE: "/api",
} as const;
