import type { Template, TechStackItemType } from "@blueprint/shared";

export interface ProjectFile {
  path: string;
  content: string;
}

export interface ProjectStructure {
  files: ProjectFile[];
  packageJson?: Record<string, any>;
  instructions?: string;
}

export function generateProjectStructure(
  template: Template,
  projectName: string = template.projectName,
): ProjectStructure {
  const files: ProjectFile[] = [];

  files.push({
    path: ".docs/blueprint.md",
    content: `# ${projectName} - Blueprint

[This would contain the AI-generated blueprint content]

## Architecture

[Architecture details would go here]

## Implementation

[Implementation details would go here]
`,
  });

  files.push({
    path: ".docs/task.md",
    content: `# ${projectName} - Tasks

[This would contain the AI-generated task breakdown]

## Priority 1
- [Task 1]

## Priority 2
- [Task 2]

## Priority 3
- [Task 3]
`,
  });

  files.push({
    path: ".docs/README.md",
    content: `# ${projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`,
  });

  const techStackFiles = generateTechStackFiles(template, projectName);
  files.push(...techStackFiles);

  return { files };
}

function generateTechStackFiles(
  template: Template,
  projectName: string,
): ProjectFile[] {
  const files: ProjectFile[] = [];

  const projectType = determineProjectType(template);

  switch (projectType) {
    case "nextjs-saas":
      files.push(...generateNextJSSaaSFiles(template, projectName));
      break;
    case "hono-api":
      files.push(...generateHonoAPIFiles(template, projectName));
      break;
    case "chrome-extension":
      files.push(...generateChromeExtensionFiles(template, projectName));
      break;
    case "cli-tool":
      files.push(...generateCliToolFiles(template, projectName));
      break;
    case "react-dashboard":
      files.push(...generateReactDashboardFiles(template, projectName));
      break;
    case "monorepo":
      files.push(...generateMonorepoFiles(template, projectName));
      break;
    default:
      files.push(...generateGenericFiles(template, projectName));
  }

  return files;
}

function determineProjectType(template: Template): string {
  const templateId = template.id;
  const hasReact = template.techStack.some((t) =>
    t.name.toLowerCase().includes("react"),
  );
  const hasNext = template.techStack.some((t) =>
    t.name.toLowerCase().includes("next"),
  );
  const hasHono = template.techStack.some((t) =>
    t.name.toLowerCase().includes("hono"),
  );
  const hasNode = template.techStack.some((t) =>
    t.name.toLowerCase().includes("node"),
  );

  if (templateId.includes("nextjs")) return "nextjs-saas";
  if (templateId.includes("hono")) return "hono-api";
  if (templateId.includes("chrome")) return "chrome-extension";
  if (templateId.includes("cli")) return "cli-tool";
  if (templateId.includes("dashboard")) return "react-dashboard";
  if (templateId.includes("monorepo")) return "monorepo";

  if (hasNext) return "nextjs-saas";
  if (hasHono) return "hono-api";
  if (hasReact) return "react-dashboard";
  if (hasNode) return "cli-tool";

  return "generic";
}

function generateNextJSSaaSFiles(
  template: Template,
  projectName: string,
): ProjectFile[] {
  const files: ProjectFile[] = [];

  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name: projectName,
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
          lint: "next lint",
        },
        dependencies: {
          next: "^14.0.0",
          react: "^18.0.0",
          "react-dom": "^18.0.0",
          "@types/node": "^20.0.0",
          "@types/react": "^18.0.0",
          "@types/react-dom": "^18.0.0",
          typescript: "^5.0.0",
          tailwindcss: "^3.0.0",
          autoprefixer: "^10.0.0",
          postcss: "^8.0.0",
          prisma: "^5.0.0",
          "@prisma/client": "^5.0.0",
          "next-auth": "^4.0.0",
          stripe: "^14.0.0",
          "@stripe/stripe-js": "^2.0.0",
          lucide: "^0.294.0",
          "react-hook-form": "^7.0.0",
          "@hookform/resolvers": "^3.0.0",
          zod: "^3.0.0",
        },
        devDependencies: {
          eslint: "^8.0.0",
          "eslint-config-next": "^14.0.0",
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: "next.config.js",
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
}

module.exports = nextConfig
`,
  });

  files.push({
    path: "tailwind.config.js",
    content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`,
  });

  files.push({
    path: "app/layout.tsx",
    content: `import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '${projectName}',
  description: '${template.defaultDescription}',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`,
  });

  files.push({
    path: "app/page.tsx",
    content: `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
        <h1 className="text-4xl font-bold">
          Welcome to ${projectName}
        </h1>
      </div>
    </main>
  )
}
`,
  });

  files.push({
    path: "app/globals.css",
    content: `@tailwind base;
@tailwind components;
@tailwind utilities;
`,
  });

  files.push({
    path: "tsconfig.json",
    content: JSON.stringify(
      {
        compilerOptions: {
          target: "es5",
          lib: ["dom", "dom.iterable", "es6"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [
            {
              name: "next",
            },
          ],
          paths: {
            "@/*": ["./*"],
          },
        },
        include: [
          "next-env.d.ts",
          "**/*.ts",
          "**/*.tsx",
          ".next/types/**/*.ts",
        ],
        exclude: ["node_modules"],
      },
      null,
      2,
    ),
  });

  return files;
}

function generateHonoAPIFiles(
  template: Template,
  projectName: string,
): ProjectFile[] {
  const files: ProjectFile[] = [];

  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name: projectName,
        version: "1.0.0",
        scripts: {
          dev: "wrangler dev",
          deploy: "wrangler deploy",
          test: "vitest",
        },
        dependencies: {
          hono: "^3.0.0",
          zod: "^3.0.0",
          "@hono/zod-validator": "^0.1.0",
        },
        devDependencies: {
          "@cloudflare/workers-types": "^4.0.0",
          wrangler: "^3.0.0",
          vitest: "^0.34.0",
          typescript: "^5.0.0",
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: "src/index.ts",
    content: `import { Hono } from 'hono';
import { z } from 'zod';
import { zValidator } from '@hono/zod-validator';

const app = new Hono();

app.get('/', (c) => {
  return c.json({ 
    message: '${projectName} API',
    version: '1.0.0',
    status: 'healthy'
  });
});

const postSchema = z.object({
  title: z.string().min(1),
  content: z.string().min(1),
});

app.post('/api/posts', zValidator('json', postSchema), (c) => {
  const { title, content } = c.req.valid('json');
  
  return c.json({
    id: Date.now(),
    title,
    content,
    createdAt: new Date().toISOString()
  });
});

export default app;
`,
  });

  files.push({
    path: "wrangler.toml",
    content: `name = "${projectName}"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "development"
`,
  });

  files.push({
    path: "tsconfig.json",
    content: JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["ES2022"],
          module: "ESNext",
          moduleResolution: "bundler",
          types: ["@cloudflare/workers-types"],
          allowSyntheticDefaultImports: true,
          esModuleInterop: true,
          strict: true,
          skipLibCheck: true,
          resolveJsonModule: true,
        },
        include: ["src/**/*.ts"],
      },
      null,
      2,
    ),
  });

  return files;
}

function generateChromeExtensionFiles(
  template: Template,
  projectName: string,
): ProjectFile[] {
  const files: ProjectFile[] = [];

  files.push({
    path: "manifest.json",
    content: JSON.stringify(
      {
        manifest_version: 3,
        name: projectName,
        version: "1.0.0",
        description: template.defaultDescription,
        action: {
          default_popup: "popup.html",
          default_title: projectName,
        },
        content_scripts: [
          {
            matches: ["<all_urls>"],
            js: ["content.js"],
          },
        ],
        background: {
          service_worker: "background.js",
        },
        permissions: ["storage", "activeTab"],
      },
      null,
      2,
    ),
  });

  files.push({
    path: "popup.html",
    content: `<!DOCTYPE html>
<html>
<head>
  <title>${projectName}</title>
  <style>
    body {
      width: 300px;
      padding: 20px;
      font-family: Arial, sans-serif;
    }
  </style>
</head>
<body>
  <h1>${projectName}</h1>
  <div id="app">
    <p>Extension popup content</p>
  </div>
  <script src="popup.js"></script>
</body>
</html>
`,
  });

  files.push({
    path: "popup.js",
    content: `document.addEventListener('DOMContentLoaded', function() {
  console.log('${projectName} popup loaded');
  
  const app = document.getElementById('app');
  app.innerHTML = '<p>Welcome to ${projectName}!</p>';
});
`,
  });

  files.push({
    path: "content.js",
    content: `console.log('${projectName} content script loaded');

document.addEventListener('click', function(event) {
  console.log('Clicked element:', event.target);
});
`,
  });

  files.push({
    path: "background.js",
    content: `console.log('${projectName} background service worker loaded');

chrome.runtime.onInstalled.addListener(function() {
  console.log('${projectName} installed');
});
`,
  });

  return files;
}

function generateCliToolFiles(
  template: Template,
  projectName: string,
): ProjectFile[] {
  const files: ProjectFile[] = [];

  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name: projectName,
        version: "1.0.0",
        description: template.defaultDescription,
        main: "dist/index.js",
        bin: {
          [projectName]: "dist/index.js",
        },
        scripts: {
          build: "tsc",
          dev: "tsc --watch",
          start: "node dist/index.js",
          test: "jest",
        },
        dependencies: {
          commander: "^11.0.0",
          inquirer: "^9.0.0",
          chalk: "^5.0.0",
          ora: "^7.0.0",
        },
        devDependencies: {
          typescript: "^5.0.0",
          "@types/node": "^20.0.0",
          "@types/inquirer": "^9.0.0",
          jest: "^29.0.0",
          "@types/jest": "^29.0.0",
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: "src/index.ts",
    content: `#!/usr/bin/env node

import { Command } from 'commander';
import inquirer from 'inquirer';
import chalk from 'chalk';
import ora from 'ora';

const program = new Command();

program
  .name('${projectName}')
  .description('${template.defaultDescription}')
  .version('1.0.0');

program
  .command('hello')
  .description('Say hello')
  .option('-n, --name <name>', 'Your name')
  .action(async (options) => {
    const spinner = ora('Processing...').start();
    
    setTimeout(() => {
      spinner.succeed();
      console.log(chalk.green(\`Hello, \${options.name || 'World'}!\`));
    }, 1000);
  });

program
  .command('interactive')
  .description('Interactive mode')
  .action(async () => {
    const answers = await inquirer.prompt([
      {
        type: 'input',
        name: 'name',
        message: 'What is your name?'
      },
      {
        type: 'list',
        name: 'favorite',
        message: 'What is your favorite color?',
        choices: ['Red', 'Blue', 'Green', 'Yellow']
      }
    ]);

    console.log(chalk.blue(\`Hello \${answers.name}!\`));
    console.log(chalk.yellow(\`Your favorite color is \${answers.favorite}\`));
  });

program.parse();
`,
  });

  files.push({
    path: "tsconfig.json",
    content: JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          module: "commonjs",
          lib: ["ES2020"],
          outDir: "./dist",
          rootDir: "./src",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          declaration: true,
          declarationMap: true,
          sourceMap: true,
        },
        include: ["src/**/*"],
        exclude: ["node_modules", "dist"],
      },
      null,
      2,
    ),
  });

  return files;
}

function generateReactDashboardFiles(
  template: Template,
  projectName: string,
): ProjectFile[] {
  const files: ProjectFile[] = [];

  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name: projectName,
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "vite",
          build: "tsc && vite build",
          preview: "vite preview",
          lint: "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
        },
        dependencies: {
          react: "^18.0.0",
          "react-dom": "^18.0.0",
          "react-router-dom": "^6.0.0",
          "react-query": "^3.0.0",
          recharts: "^2.0.0",
          "lucide-react": "^0.294.0",
          tailwindcss: "^3.0.0",
          autoprefixer: "^10.0.0",
          postcss: "^8.0.0",
          "@supabase/supabase-js": "^2.0.0",
        },
        devDependencies: {
          "@types/react": "^18.0.0",
          "@types/react-dom": "^18.0.0",
          "@vitejs/plugin-react": "^4.0.0",
          eslint: "^8.0.0",
          "eslint-plugin-react-hooks": "^4.0.0",
          "eslint-plugin-react-refresh": "^0.4.0",
          typescript: "^5.0.0",
          vite: "^4.0.0",
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: "vite.config.ts",
    content: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`,
  });

  files.push({
    path: "src/App.tsx",
    content: `import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from 'react-query';
import Dashboard from './components/Dashboard';
import './App.css';

const queryClient = new QueryClient();

function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <Router>
        <div className="App">
          <Routes>
            <Route path="/" element={<Dashboard />} />
          </Routes>
        </div>
      </Router>
    </QueryClientProvider>
  );
}

export default App;
`,
  });

  files.push({
    path: "src/components/Dashboard.tsx",
    content: `import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const Dashboard = () => {
  const data = [
    { name: 'Jan', value: 400 },
    { name: 'Feb', value: 300 },
    { name: 'Mar', value: 600 },
    { name: 'Apr', value: 800 },
    { name: 'May', value: 500 },
  ];

  return (
    <div className="p-6">
      <h1 className="text-3xl font-bold mb-6">${projectName} Dashboard</h1>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <div className="bg-white p-6 rounded-lg shadow">
          <h3 className="text-sm font-medium text-gray-500">Total Users</h3>
          <p className="text-2xl font-bold text-gray-900">1,234</p>
        </div>
        <div className="bg-white p-6 rounded-lg shadow">
          <h3 className="text-sm font-medium text-gray-500">Revenue</h3>
          <p className="text-2xl font-bold text-gray-900">$12,345</p>
        </div>
        <div className="bg-white p-6 rounded-lg shadow">
          <h3 className="text-sm font-medium text-gray-500">Orders</h3>
          <p className="text-2xl font-bold text-gray-900">567</p>
        </div>
        <div className="bg-white p-6 rounded-lg shadow">
          <h3 className="text-sm font-medium text-gray-500">Growth</h3>
          <p className="text-2xl font-bold text-gray-900">+12%</p>
        </div>
      </div>

      <div className="bg-white p-6 rounded-lg shadow">
        <h2 className="text-xl font-bold mb-4">Monthly Overview</h2>
        <ResponsiveContainer width="100%" height={300}>
          <BarChart data={data}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="name" />
            <YAxis />
            <Tooltip />
            <Bar dataKey="value" fill="#3b82f6" />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
};

export default Dashboard;
`,
  });

  files.push({
    path: "src/App.css",
    content: `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  background-color: #f3f4f6;
}
`,
  });

  files.push({
    path: "tsconfig.json",
    content: JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
          noUnusedLocals: true,
          noUnusedParameters: true,
          noFallthroughCasesInSwitch: true,
        },
        include: ["src"],
        references: [{ path: "./tsconfig.node.json" }],
      },
      null,
      2,
    ),
  });

  return files;
}

function generateMonorepoFiles(
  template: Template,
  projectName: string,
): ProjectFile[] {
  const files: ProjectFile[] = [];

  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name: projectName,
        version: "1.0.0",
        private: true,
        workspaces: ["packages/*", "apps/*"],
        scripts: {
          build: "npm run build --workspaces",
          dev: "npm run dev --workspaces",
          test: "npm run test --workspaces",
          lint: "eslint . --ext .ts,.tsx",
        },
        devDependencies: {
          typescript: "^5.0.0",
          eslint: "^8.0.0",
          "@typescript-eslint/eslint-plugin": "^6.0.0",
          "@typescript-eslint/parser": "^6.0.0",
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: "packages/shared/package.json",
    content: JSON.stringify(
      {
        name: `${projectName}-shared`,
        version: "1.0.0",
        main: "dist/index.js",
        types: "dist/index.d.ts",
        scripts: {
          build: "tsc",
          dev: "tsc --watch",
        },
        dependencies: {
          zod: "^3.0.0",
        },
        devDependencies: {
          typescript: "^5.0.0",
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: "packages/shared/src/index.ts",
    content: `export interface User {
  id: string;
  name: string;
  email: string;
}

export const API_BASE_URL = process.env.API_BASE_URL || 'http://localhost:3000';
`,
  });

  files.push({
    path: "apps/web/package.json",
    content: JSON.stringify(
      {
        name: `${projectName}-web`,
        version: "1.0.0",
        private: true,
        scripts: {
          dev: "vite",
          build: "tsc && vite build",
          preview: "vite preview",
        },
        dependencies: {
          react: "^18.0.0",
          "react-dom": "^18.0.0",
          [`${projectName}-shared`]: "workspace:*",
        },
        devDependencies: {
          "@types/react": "^18.0.0",
          "@types/react-dom": "^18.0.0",
          "@vitejs/plugin-react": "^4.0.0",
          typescript: "^5.0.0",
          vite: "^4.0.0",
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: "apps/api/package.json",
    content: JSON.stringify(
      {
        name: `${projectName}-api`,
        version: "1.0.0",
        main: "dist/index.js",
        scripts: {
          dev: "tsx watch src/index.ts",
          build: "tsc",
          start: "node dist/index.js",
        },
        dependencies: {
          hono: "^3.0.0",
          [`${projectName}-shared`]: "workspace:*",
        },
        devDependencies: {
          typescript: "^5.0.0",
          tsx: "^4.0.0",
        },
      },
      null,
      2,
    ),
  });

  return files;
}

function generateGenericFiles(
  template: Template,
  projectName: string,
): ProjectFile[] {
  const files: ProjectFile[] = [];

  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name: projectName,
        version: "1.0.0",
        description: template.defaultDescription,
        scripts: {
          start: "node index.js",
          dev: "node --watch index.js",
        },
        dependencies: {},
        devDependencies: {
          typescript: "^5.0.0",
        },
      },
      null,
      2,
    ),
  });

  files.push({
    path: "README.md",
    content: `# ${projectName}

${template.defaultDescription}

## Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Run the development server:
\`\`\`bash
npm run dev
\`\`\`

## Tech Stack

${template.techStack.map((tech) => `- ${tech.name} (${tech.category})`).join("\n")}

## Features

${template.features.map((feature) => `- ${feature}`).join("\n")}

## License

MIT
`,
  });

  files.push({
    path: "index.js",
    content: `console.log('Welcome to ${projectName}!');

// Your application code goes here
`,
  });

  return files;
}
