import JSZip from 'jszip';

interface ExportFiles {
  blueprint: string;
  tasks: string;
  projectName: string;
}

/**
 * Generate and download a ZIP file containing the docs folder
 */
export async function exportAsZip(files: ExportFiles): Promise<void> {
  const zip = new JSZip();
  const docsFolder = zip.folder('.docs');

  if (!docsFolder) {
    throw new Error('Failed to create docs folder');
  }

  // Add blueprint.md
  if (files.blueprint) {
    docsFolder.file('blueprint.md', files.blueprint);
  }

  // Add task.md
  if (files.tasks) {
    docsFolder.file('task.md', files.tasks);
  }

  // Add a README for the docs folder
  docsFolder.file('README.md', `# ${files.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`);

  // Generate the ZIP
  const blob = await zip.generateAsync({ 
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 }
  });

  // Trigger download
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${files.projectName.toLowerCase().replace(/\s+/g, '-')}-docs.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Copy text to clipboard with fallback
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand('copy');
    document.body.removeChild(textarea);
    return success;
  }
}

/**
 * Format markdown for IDE pasting (normalize line endings)
 */
export function formatForIDE(content: string): string {
  return content
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .trim();
}
