import JSZip from "jszip";
import { TechStackItemType } from "@blueprint/shared";

interface ExportFiles {
  blueprint: string;
  tasks: string;
  projectName: string;
  techStack?: TechStackItemType[];
  description?: string;
  targetAudience?: string;
  features?: string[];
}

interface ProjectTemplate {
  files: Record<string, string>;
  folders: string[];
  packageJson?: Record<string, any>;
  readme?: string;
}

export interface ZipGenerationProgress {
  stage: string;
  progress: number;
  total: number;
}

export type ZipGenerationCallback = (progress: ZipGenerationProgress) => void;

function generateProjectTemplate(files: ExportFiles): ProjectTemplate {
  const template: ProjectTemplate = {
    files: {},
    folders: [".docs", "src"],
  };

  template.files[".docs/blueprint.md"] = files.blueprint;
  template.files[".docs/task.md"] = files.tasks;
  template.files[".docs/README.md"] = `# ${files.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`;

  if (files.techStack && files.techStack.length > 0) {
    const primaryStack = files.techStack[0];
    if (!primaryStack) return generateGenericTemplate(files);

    const stackCategory = primaryStack.category;

    switch (stackCategory) {
      case "frontend":
        if (
          files.techStack.some((t) => t.name.toLowerCase().includes("react"))
        ) {
          return generateReactTemplate(files);
        } else if (
          files.techStack.some((t) => t.name.toLowerCase().includes("vue"))
        ) {
          return generateVueTemplate(files);
        } else if (
          files.techStack.some((t) => t.name.toLowerCase().includes("angular"))
        ) {
          return generateAngularTemplate(files);
        }
        break;

      case "backend":
        if (
          files.techStack.some((t) => t.name.toLowerCase().includes("node"))
        ) {
          return generateNodeTemplate(files);
        } else if (
          files.techStack.some((t) => t.name.toLowerCase().includes("python"))
        ) {
          return generatePythonTemplate(files);
        } else if (
          files.techStack.some((t) => t.name.toLowerCase().includes("java"))
        ) {
          return generateJavaTemplate(files);
        }
        break;

      case "database":
        return generateDatabaseTemplate(files);

      case "hosting":
        return generateStaticSiteTemplate(files);

      case "ai":
        return generateGenericTemplate(files);

      case "testing":
        return generateGenericTemplate(files);

      case "styling":
        return generateStaticSiteTemplate(files);

      case "other":
        return generateGenericTemplate(files);
    }
  }

  return generateGenericTemplate(files);
}

function generateReactTemplate(files: ExportFiles): ProjectTemplate {
  const template: ProjectTemplate = {
    files: {},
    folders: [".docs", "src", "public"],
  };

  template.files["package.json"] = JSON.stringify(
    {
      name: files.projectName.toLowerCase().replace(/\s+/g, "-"),
      version: "1.0.0",
      description: files.description || "",
      scripts: {
        dev: "vite",
        build: "tsc && vite build",
        preview: "vite preview",
        lint: "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
      },
      dependencies: {
        react: "^18.2.0",
        "react-dom": "^18.2.0",
      },
      devDependencies: {
        "@types/react": "^18.2.43",
        "@types/react-dom": "^18.2.17",
        "@typescript-eslint/eslint-plugin": "^6.14.0",
        "@typescript-eslint/parser": "^6.14.0",
        "@vitejs/plugin-react": "^4.2.1",
        eslint: "^8.55.0",
        "eslint-plugin-react-hooks": "^4.6.0",
        "eslint-plugin-react-refresh": "^0.4.5",
        typescript: "^5.2.2",
        vite: "^5.0.8",
      },
    },
    null,
    2,
  );

  template.files["vite.config.ts"] = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`;

  template.files["tsconfig.json"] = JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        useDefineForClassFields: true,
        lib: ["ES2020", "DOM", "DOM.Iterable"],
        module: "ESNext",
        skipLibCheck: true,
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: "react-jsx",
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true,
      },
      include: ["src"],
      references: [{ path: "./tsconfig.node.json" }],
    },
    null,
    2,
  );

  template.files["src/App.tsx"] = `import { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <h1>${files.projectName}</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
    </div>
  )
}

export default App`;

  template.files["src/main.tsx"] = `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`;

  template.files["src/index.css"] = `:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;

  color-scheme: light dark;
  color: rgba(255, 255, 255, 0.87);
  background-color: #242424;

  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -webkit-text-size-adjust: 100%;
}

a {
  font-weight: 500;
  color: #646cff;
  text-decoration: inherit;
}
a:hover {
  color: #535bf2;
}

body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
}
button:hover {
  border-color: #646cff;
}
button:focus,
button:focus-visible {
  outline: 4px auto -webkit-focus-ring-color;
}

@media (prefers-color-scheme: light) {
  :root {
    color: #213547;
    background-color: #ffffff;
  }
  a:hover {
    color: #747bff;
  }
  button {
    background-color: #f9f9f9;
  }
}`;

  template.files["src/App.css"] = `#root {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.react:hover {
  filter: drop-shadow(0 0 2em #61dafbaa);
}

@keyframes logo-spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}

@media (prefers-reduced-motion: no-preference) {
  a:nth-of-type(2).logo {
    animation: logo-spin infinite 20s linear;
  }
}

.card {
  padding: 2em;
}

.read-the-docs {
  color: #888;
}`;

  template.files["public/index.html"] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${files.projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`;

  template.files[".docs/blueprint.md"] = files.blueprint;
  template.files[".docs/task.md"] = files.tasks;
  template.files[".docs/README.md"] = `# ${files.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`;

  return template;
}

function generateNodeTemplate(files: ExportFiles): ProjectTemplate {
  const template: ProjectTemplate = {
    files: {},
    folders: [".docs", "src", "tests"],
  };

  template.files["package.json"] = JSON.stringify(
    {
      name: files.projectName.toLowerCase().replace(/\s+/g, "-"),
      version: "1.0.0",
      description: files.description || "",
      main: "dist/index.js",
      scripts: {
        dev: "tsx watch src/index.ts",
        build: "tsc",
        start: "node dist/index.js",
        test: "jest",
        lint: "eslint src --ext .ts",
      },
      dependencies: {
        express: "^4.18.2",
        cors: "^2.8.5",
        helmet: "^7.1.0",
        zod: "^3.22.4",
      },
      devDependencies: {
        "@types/express": "^4.17.21",
        "@types/cors": "^2.8.17",
        "@types/node": "^20.10.5",
        "@typescript-eslint/eslint-plugin": "^6.14.0",
        "@typescript-eslint/parser": "^6.14.0",
        eslint: "^8.55.0",
        jest: "^29.7.0",
        tsx: "^4.6.2",
        typescript: "^5.3.3",
      },
    },
    null,
    2,
  );

  template.files["src/index.ts"] = `import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { z } from 'zod';

const app = express();
const PORT = process.env.PORT || 3000;

app.use(helmet());
app.use(cors());
app.use(express.json());

app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

app.get('/api', (req, res) => {
  res.json({ message: 'Welcome to ${files.projectName} API' });
});

app.listen(PORT, () => {
  console.log(\`🚀 Server running on port \${PORT}\`);
});

export default app;`;

  template.files["tsconfig.json"] = JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "commonjs",
        lib: ["ES2020"],
        outDir: "./dist",
        rootDir: "./src",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        declaration: true,
        declarationMap: true,
        sourceMap: true,
      },
      include: ["src/**/*"],
      exclude: ["node_modules", "dist", "tests"],
    },
    null,
    2,
  );

  template.files[".docs/blueprint.md"] = files.blueprint;
  template.files[".docs/task.md"] = files.tasks;
  template.files[".docs/README.md"] = `# ${files.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`;

  return template;
}

function generatePythonTemplate(files: ExportFiles): ProjectTemplate {
  const template: ProjectTemplate = {
    files: {},
    folders: [".docs", "src", "tests"],
  };

  template.files["requirements.txt"] = `fastapi==0.104.1
uvicorn==0.24.0
pydantic==2.5.0
python-multipart==0.0.6
pytest==7.4.3
pytest-asyncio==0.21.1`;

  template.files["src/main.py"] = `from fastapi import FastAPI
from pydantic import BaseModel
from typing import Optional
import uvicorn

app = FastAPI(
    title="${files.projectName}",
    description="${files.description || "API generated from blueprint"}",
    version="1.0.0"
)

class HealthResponse(BaseModel):
    status: str
    timestamp: str

@app.get("/health", response_model=HealthResponse)
async def health_check():
    return HealthResponse(
        status="ok",
        timestamp="2024-01-01T00:00:00Z"
    )

@app.get("/")
async def root():
    return {"message": "Welcome to ${files.projectName} API"}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)`;

  template.files["pyproject.toml"] = `[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "${files.projectName.toLowerCase().replace(/\s+/g, "-")}"
version = "1.0.0"
description = "${files.description || ""}"
authors = [{name = "Generated", email = "dev@example.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/example/${files.projectName.toLowerCase().replace(/\s+/g, "-")}"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]`;

  template.files[".docs/blueprint.md"] = files.blueprint;
  template.files[".docs/task.md"] = files.tasks;
  template.files[".docs/README.md"] = `# ${files.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`;

  return template;
}

function generateStaticSiteTemplate(files: ExportFiles): ProjectTemplate {
  const template: ProjectTemplate = {
    files: {},
    folders: [".docs", "assets", "css", "js"],
  };

  template.files["index.html"] = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${files.projectName}</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="icon" href="assets/favicon.ico">
</head>
<body>
    <header>
        <nav>
            <h1>${files.projectName}</h1>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section id="home">
            <h2>Welcome to ${files.projectName}</h2>
            <p>${files.description || "A static website generated from blueprint"}</p>
        </section>

        <section id="about">
            <h2>About</h2>
            <p>This is a static website template generated from your blueprint.</p>
        </section>

        <section id="contact">
            <h2>Contact</h2>
            <p>Get in touch with us for more information.</p>
        </section>
    </main>

    <footer>
        <p>&copy; 2024 ${files.projectName}. All rights reserved.</p>
    </footer>

    <script src="js/main.js"></script>
</body>
</html>`;

  template.files["css/style.css"] = `* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #333;
}

header {
    background: #2c3e50;
    color: white;
    padding: 1rem 0;
    position: sticky;
    top: 0;
    z-index: 100;
}

nav {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 2rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

nav h1 {
    font-size: 1.5rem;
}

nav ul {
    display: flex;
    list-style: none;
    gap: 2rem;
}

nav a {
    color: white;
    text-decoration: none;
    transition: color 0.3s;
}

nav a:hover {
    color: #3498db;
}

main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}

section {
    margin-bottom: 4rem;
}

section h2 {
    font-size: 2rem;
    margin-bottom: 1rem;
    color: #2c3e50;
}

section p {
    font-size: 1.1rem;
    line-height: 1.8;
}

footer {
    background: #34495e;
    color: white;
    text-align: center;
    padding: 2rem 0;
    margin-top: 4rem;
}

@media (max-width: 768px) {
    nav {
        flex-direction: column;
        gap: 1rem;
    }
    
    nav ul {
        gap: 1rem;
    }
    
    main {
        padding: 1rem;
    }
}`;

  template.files["js/main.js"] =
    `document.addEventListener('DOMContentLoaded', function() {
    console.log('${files.projectName} loaded successfully');
    
    const navLinks = document.querySelectorAll('nav a[href^="#"]');
    
    navLinks.forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            
            const targetId = this.getAttribute('href').substring(1);
            const targetElement = document.getElementById(targetId);
            
            if (targetElement) {
                targetElement.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });
    
    let lastScroll = 0;
    const header = document.querySelector('header');
    
    window.addEventListener('scroll', function() {
        const currentScroll = window.pageYOffset;
        
        if (currentScroll > 100) {
            header.style.background = 'rgba(44, 62, 80, 0.95)';
            header.style.backdropFilter = 'blur(10px)';
        } else {
            header.style.background = '#2c3e50';
            header.style.backdropFilter = 'none';
        }
        
        lastScroll = currentScroll;
    });
});`;

  template.files[".docs/blueprint.md"] = files.blueprint;
  template.files[".docs/task.md"] = files.tasks;
  template.files[".docs/README.md"] = `# ${files.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`;

  return template;
}

function generateGenericTemplate(files: ExportFiles): ProjectTemplate {
  const template: ProjectTemplate = {
    files: {},
    folders: [".docs", "src"],
  };

  template.files["README.md"] = `# ${files.projectName}

${files.description || "A project generated from blueprint"}

## Getting Started

This project was generated using the Blueprint Generator. The documentation folder contains detailed architectural specifications and implementation tasks.

## Documentation

See the \`.docs/\` folder for:
- \`blueprint.md\` - Architectural blueprint and technical specifications
- \`task.md\` - Prioritized task breakdown for implementation

## Tech Stack

${files.techStack?.map((t) => `- ${t.name}`).join("\n") || "Not specified"}

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`;

  template.files[".docs/blueprint.md"] = files.blueprint;
  template.files[".docs/task.md"] = files.tasks;
  template.files[".docs/README.md"] = `# ${files.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`;

  return template;
}

function generateVueTemplate(files: ExportFiles): ProjectTemplate {
  return generateGenericTemplate(files);
}

function generateAngularTemplate(files: ExportFiles): ProjectTemplate {
  return generateGenericTemplate(files);
}

function generateDatabaseTemplate(files: ExportFiles): ProjectTemplate {
  return generateGenericTemplate(files);
}

function generateReactNativeTemplate(files: ExportFiles): ProjectTemplate {
  return generateGenericTemplate(files);
}

function generateFlutterTemplate(files: ExportFiles): ProjectTemplate {
  return generateGenericTemplate(files);
}

function generateJavaTemplate(files: ExportFiles): ProjectTemplate {
  return generateGenericTemplate(files);
}

export async function exportAsZip(
  files: ExportFiles,
  onProgress?: ZipGenerationCallback,
): Promise<void> {
  const zip = new JSZip();

  try {
    onProgress?.({
      stage: "Generating project template",
      progress: 0,
      total: 100,
    });

    const template = generateProjectTemplate(files);

    onProgress?.({
      stage: "Creating folder structure",
      progress: 20,
      total: 100,
    });

    template.folders.forEach((folder) => {
      zip.folder(folder);
    });

    onProgress?.({ stage: "Adding files", progress: 40, total: 100 });

    const fileEntries = Object.entries(template.files);
    fileEntries.forEach(([path, content], index) => {
      zip.file(path, content);

      const progress = 40 + Math.floor((index / fileEntries.length) * 40);
      onProgress?.({
        stage: `Adding files (${index + 1}/${fileEntries.length})`,
        progress,
        total: 100,
      });
    });

    onProgress?.({ stage: "Generating ZIP archive", progress: 80, total: 100 });

    const blob = await zip.generateAsync({
      type: "blob",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    onProgress?.({ stage: "Preparing download", progress: 95, total: 100 });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;

    const date = new Date().toISOString().split("T")[0];
    const sanitizedName = files.projectName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");

    link.download = `${sanitizedName}-${date}.zip`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    onProgress?.({ stage: "Complete", progress: 100, total: 100 });
  } catch (error) {
    console.error("Error generating ZIP:", error);
    throw new Error(
      `Failed to generate ZIP file: ${error instanceof Error ? error.message : "Unknown error"}`,
    );
  }
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const textarea = document.createElement("textarea");
    textarea.value = text;
    textarea.style.position = "fixed";
    textarea.style.left = "-9999px";
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand("copy");
    document.body.removeChild(textarea);
    return success;
  }
}

export function formatForIDE(content: string): string {
  return content.replace(/\r\n/g, "\n").replace(/\r/g, "\n").trim();
}
