import JSZip from "jszip";
import { generateProjectStructure } from "@blueprint/shared";
import type { Template } from "@blueprint/shared";

interface ExportFiles {
  blueprint: string;
  tasks: string;
  projectName: string;
}

interface ProjectExportOptions extends ExportFiles {
  template?: Template;
  includeFullProject?: boolean;
}

export async function exportAsZip(files: ExportFiles): Promise<void> {
  const zip = new JSZip();
  const docsFolder = zip.folder(".docs");

  if (!docsFolder) {
    throw new Error("Failed to create docs folder");
  }

  if (files.blueprint) {
    docsFolder.file("blueprint.md", files.blueprint);
  }

  if (files.tasks) {
    docsFolder.file("task.md", files.tasks);
  }

  docsFolder.file(
    "README.md",
    `# ${files.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`,
  );

  const blob = await zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${files.projectName.toLowerCase().replace(/\s+/g, "-")}-docs.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function exportProjectAsZip(
  options: ProjectExportOptions,
): Promise<void> {
  const zip = new JSZip();

  if (options.includeFullProject && options.template) {
    const projectStructure = generateProjectStructure(
      options.template,
      options.projectName,
    );

    for (const file of projectStructure.files) {
      zip.file(file.path, file.content);
    }

    const blueprintContent = options.blueprint || "";
    const tasksContent = options.tasks || "";

    zip.file(".docs/blueprint.md", blueprintContent);
    zip.file(".docs/task.md", tasksContent);
    zip.file(
      ".docs/README.md",
      `# ${options.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`,
    );

    zip.file(
      "README.md",
      `# ${options.projectName}

${options.template.defaultDescription}

## Quick Start

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Start development:
\`\`\`bash
npm run dev
\`\`\`

## Tech Stack

${options.template.techStack.map((tech) => `- ${tech.name} (${tech.category})`).join("\n")}

## Features

${options.template.features.map((feature) => `- ${feature}`).join("\n")}

## Documentation

See the \`.docs/\` folder for AI-generated architectural blueprints and implementation tasks.

## License

MIT
`,
    );
  } else {
    const docsFolder = zip.folder(".docs");
    if (!docsFolder) {
      throw new Error("Failed to create docs folder");
    }

    if (options.blueprint) {
      docsFolder.file("blueprint.md", options.blueprint);
    }

    if (options.tasks) {
      docsFolder.file("task.md", options.tasks);
    }

    docsFolder.file(
      "README.md",
      `# ${options.projectName} - Documentation

This folder contains AI-generated documentation for your project.

## Files

- **blueprint.md** - Architectural blueprint and technical specifications
- **task.md** - Prioritized task breakdown for implementation

## Usage

These files are designed for use with autonomous development agents.
Place this .docs folder in your project root to enable agent-assisted development.

---
Generated by [Blueprint Generator](https://blueprint-generator.pages.dev)
Generated at: ${new Date().toISOString()}
`,
    );
  }

  const blob = await zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const filename = options.includeFullProject
    ? `${options.projectName.toLowerCase().replace(/\s+/g, "-")}-project.zip`
    : `${options.projectName.toLowerCase().replace(/\s+/g, "-")}-docs.zip`;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const textarea = document.createElement("textarea");
    textarea.value = text;
    textarea.style.position = "fixed";
    textarea.style.left = "-9999px";
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand("copy");
    document.body.removeChild(textarea);
    return success;
  }
}

export function formatForIDE(content: string): string {
  return content.replace(/\r\n/g, "\n").replace(/\r/g, "\n").trim();
}
